# Generated by Django 4.0.2 on 2022-05-05 10:39

from django.db import migrations, models


def populate_categorias(apps, schema_editor):
    Categoria = apps.get_model('loja', 'Categoria')
    
    nomes = [
        "Carros e Motocicletas", 
        "Imóveis e Casas", 
        "Casa e Jardim", 
        "Moda e Beleza",
        "Família, Criança e Bebê",
        "Multimídia e Eletrônica",
        "Empregos",
        "Shows e Ingressos",
        "Lazer, Hobby e Diversão",
        "Música, Cinema e Livros",
        "Doação e trocas",
        "Animais",
        "Aulas e Cursos"
        ]
    icones = [
        "fa-motorcycle",
        "fa-home",
        "fa-tree",
        "fa-tag",
        "fa-child",
        "fa-tablet",
        "fa-suitcase",
        "fa-ticket-alt",
        "fa-gamepad",
        "fa-book",
        "fa-handshake",
        "fa-paw",
        "fa-graduation-cap"
    ]

    for idx, obj in enumerate(nomes):
        c=Categoria()
        c.nome=obj
        c.icone=icones[idx]
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(max_length=255, verbose_name='ícone'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='preço'),
        ),
        migrations.RunPython(populate_categorias),
    ]
