# Generated by Django 4.2.7 on 2025-02-11 20:03

from django.conf import settings
from django.db import migrations


def populate_categorias(apps, schema_editor):
    Categoria = apps.get_model('loja', 'Categoria')

    nomes = [
        "Carros e Motocicletas",
        "Imóveis e Casas",
        "Casa e Jardim",
        "Moda e Beleza",
        "Família, Criança e Bebê",
        "Multimídia e Eletrônica",
        "Empregos",
        "Shows e Ingressos",
        "Lazer, Hobby e Diversão",
        "Música, Cinema e Livros",
        "Doação e trocas",
        "Animais",
        "Aulas e Cursos"
    ]

    for nome in nomes:
        categoria = Categoria()
        categoria._current_language = 'pt'
        categoria.nome = nome
        categoria.save()


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_categorias)
    ]
