# Generated by Django 4.0.2 on 2022-05-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(max_length=255, verbose_name='ícone'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='preço'),
        ),
    ]
