# Generated by Django 4.1.4 on 2023-01-10 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_remove_categoria_icone_remove_categoria_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='loja.categoria'),
        ),
        migrations.AlterField(
            model_name='categoriatranslation',
            name='icone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
