# Generated by Django 4.2.7 on 2025-02-12 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_auto_20250211_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='categoria',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='sub_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='anuncios', to='loja.subcategoria'),
        ),
    ]
