# Generated by Django 4.2.7 on 2025-02-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_remove_anuncio_categoria_anuncio_sub_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='custo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
