# Generated by Django 4.1.4 on 2023-01-24 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_categoria_categoria_alter_categoriatranslation_icone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
    ]
