# Generated by Django 4.1.4 on 2023-01-24 00:26

from django.db import migrations
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist


def populate_categorias(apps, schema_editor):
    Categoria = apps.get_model('loja', 'Categoria')
    CategoriaTranslation = apps.get_model('loja', 'CategoriaTranslation')
    
    nomes = [
        "Carros e Motocicletas", 
        "Imóveis e Casas", 
        "Casa e Jardim", 
        "Moda e Beleza",
        "Família, Criança e Bebê",
        "Multimídia e Eletrônica",
        "Empregos",
        "Shows e Ingressos",
        "Lazer, Hobby e Diversão",
        "Música, Cinema e Livros",
        "Doação e trocas",
        "Animais",
        "Aulas e Cursos"
        ]
    icones = [
        "fa-motorcycle",
        "fa-home",
        "fa-tree",
        "fa-tag",
        "fa-child",
        "fa-tablet",
        "fa-suitcase",
        "fa-ticket-alt",
        "fa-gamepad",
        "fa-book",
        "fa-handshake",
        "fa-paw",
        "fa-graduation-cap"
    ]

    for idx, categoria in enumerate(Categoria.objects.all()):
        categoria._current_language='pt'
        categoria.nome=nomes[idx]
        categoria.icone=icones[idx]
        categoria.save()

        c=CategoriaTranslation()
        c.master_id=categoria.pk
        c.language_code=settings.LANGUAGE_CODE
        c.nome=categoria.nome
        c.icone=categoria.icone
        c._parler_meta = []
        c.save()



class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_categoria_options'),
    ]

    operations = [
        migrations.RunPython(populate_categorias),
    ]
