# Generated by Django 4.2.7 on 2025-02-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_anuncio_custo_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'Industrial supplier'), (2, 'Private provider')], default=1),
        ),
    ]
