# Generated by Django 4.0.9 on 2023-02-25 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_migrate_translatable_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='view', to='loja.produto')),
            ],
        ),
    ]
