# Generated by Django 4.2.7 on 2025-02-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_fotoanuncio_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotoanuncio',
            name='url_imagem',
        ),
    ]
