# Generated by Django 4.2.7 on 2025-02-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_remove_fotoanuncio_url_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotoanuncio',
            options={'ordering': ['ordem']},
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
