# Generated by Django 4.2.20 on 2025-03-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_alter_fotoanuncio_options_alter_anuncio_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
