# Generated by Django 4.2.20 on 2025-03-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_oferta_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(null=True, upload_to='usuario/foto', verbose_name=''),
        ),
    ]
