# Generated by Django 4.2.7 on 2023-12-12 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(null=True, upload_to=None, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='localizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.endereco'),
        ),
    ]
