# Generated by Django 4.2.7 on 2023-12-13 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_alter_customuser_foto_alter_customuser_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
