# Generated by Django 4.2.20 on 2025-04-03 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_chatroom_mensagem_chat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='mensagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ofertas', to='loja.mensagem'),
        ),
    ]
