# Generated by Django 4.2.20 on 2025-07-06 18:08

from django.db import migrations, models
import loja.fields


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_alter_oferta_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(null=True, upload_to=loja.fields.gerar_nome_aleatorio, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='fotoanuncio',
            name='imagem',
            field=models.ImageField(null=True, upload_to=loja.fields.gerar_nome_aleatorio),
        ),
        migrations.AlterField(
            model_name='imagemproduto',
            name='imagem',
            field=models.ImageField(upload_to=loja.fields.gerar_nome_aleatorio, verbose_name=''),
        ),
    ]
