# Generated by Django 4.2.7 on 2024-07-17 00:47

from django.db import migrations

def populate_subcategorias(apps, schema_editor):
    Categoria = apps.get_model('loja', 'Categoria')
    SubCategoria = apps.get_model('loja', 'SubCategoria')

    categorias_names = ['Aulas', 'Animais', 'Doação', 'Música', 'Lazer', 'Shows', 'Empregos', 'Multimídia', 'Família', 'Moda', 'Casa', 'Imóveis', 'Carros']

    subcategories = {
        'Aulas': ['Tutoria', 'Educação continuada', 'Aulas de dança', 'Cursos de esportes', 'Música e canto', 'Design de arte',
                  'Cozinhar assados', 'Esotérico e Espiritual', 'Cursos de informática', 'Beleza', 'Cursos de idiomas', 'Mais'],
        'Animais': ['Cães e acessórios', 'Mais', 'Aves e Acessórios', 'Animais desaparecidos', 'Cuidado e treinamento de animais',
                    'Cavalos e Acessórios', 'Pequenos animais e acessórios', 'Peixes e Acessórios', 'Gatos e acessórios',
                    'Répteis e acessórios'],
        'Doação': ['Emprestar', 'Para trocar', 'Para doar']
    }

    for name in categorias_names:
        categoria = Categoria.objects.translated(nome__contains=name).first()


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0015_subcategoria'),
    ]

    operations = [
        migrations.RunPython(populate_subcategorias)
    ]
