# Generated by Django 4.2.7 on 2025-01-30 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0018_remove_categoria_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaArte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='loja.subcategoria')),
            ],
        ),
    ]
