# Generated by Django 4.2.7 on 2025-02-01 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0022_fotoanuncio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mensagem', models.TextField()),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='loja.anuncio')),
            ],
        ),
    ]
