# Generated by Django 4.2.7 on 2025-02-01 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0023_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='loja.anuncio')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='loja.oferta')),
            ],
        ),
    ]
