# Generated by Django 4.2.7 on 2025-02-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0025_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'Industrial supplier')], default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='commercial_provider',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_size',
            field=models.IntegerField(choices=[(1, 'Small business owner'), (2, 'Entrepreneur (with VAT)')], default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='conditions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='legal_notice',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postcode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='protection_notice',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='right_withdrawal',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_number',
            field=models.IntegerField(default=0),
        ),
    ]
