# Generated by Django 4.2.7 on 2025-02-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0026_customuser_account_type_customuser_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.TextField()),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebidas', to='loja.customuser')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviadas', to='loja.customuser')),
            ],
        ),
    ]
