# Generated by Django 4.2.7 on 2025-02-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0027_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='codigo_postal',
            field=models.CharField(default='', max_length=10),
        ),
    ]
