# Generated by Django 4.2.7 on 2025-02-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0028_anuncio_codigo_postal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriatranslation',
            name='icone',
        ),
    ]
