# Generated by Django 4.2.7 on 2025-02-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0029_remove_categoriatranslation_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtotranslation',
            name='preco',
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
