# Generated by Django 4.2.7 on 2025-02-10 11:37

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0030_remove_produtotranslation_preco_produto_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoriaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(
                    db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=123)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True,
                 on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='loja.subcategoria')),
            ],
            options={
                'verbose_name': 'sub categoria Translation',
                'db_table': 'loja_subcategoria_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model)
        ),
    ]
