# Generated by Django 4.2.7 on 2025-02-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0032_migrate_subcategoria_translatable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='nome',
        ),
    ]
