# Generated by Django 4.2.7 on 2025-02-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0033_remove_subcategoria_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='data_venda',
            new_name='data_publicacao',
        ),
    ]
