# Generated by Django 4.2.7 on 2025-02-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0034_rename_data_venda_anuncio_data_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='pagamento_paypal',
            field=models.BooleanField(default=False),
        ),
    ]
