# Generated by Django 4.2.7 on 2025-02-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0035_anuncio_pagamento_paypal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
