services:
  db:
    image: postgres:15.1
    volumes:
      - "bancoecommerce:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - "5432:5432"

volumes:
   bancoecommerce:
