services:
  db:
    image: postgres:15.1
    volumes:
      - "bancoecommerce:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--appendonly", "yes"]


volumes:
   bancoecommerce:
