services:
  db:
    image: postgres:15.1
    volumes:
      - "bancodados:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432

  web:
    build: .
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=marcommerce.settings.devp
    depends_on:
      - db

  redis:
    image: redis:7
    expose:
      - 6379
    command: ["redis-server", "--appendonly", "yes"]

volumes:
   bancodados:
