services:
  db:
    image: postgres:15.1
    container_name: marcommerce-db
    volumes:
      - "bancodados:/var/lib/postgresql/data"
    expose:
      - 5432
    env_file:
     - .env

  web:
    build: .
    container_name: marcommerce-web
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    expose:
      - 8080
    env_file:
     - .env
    depends_on:
      - db

  redis:
    container_name: marcommerce-redis
    image: redis:7
    expose:
      - 6379
    command: ["redis-server", "--appendonly", "yes"]

volumes:
   bancodados:
